### ISSUE TITLE
Coriolis 3.0 Todo Summary

### ISSUE THREAD

**Issue by willyb321** [EDCD/coriolis#190]
# Summary of things left to do for 3.0
> Sorted by priority
- [x] 3.0 Updates - Tech broker stuff remains.
- [ ] Coriolis serverside. https://github.com/strideynet/Orbis
- [x] 3.0 Journal imports (with engineering) - Currently on ~~beta~~ live. Keep your EDMC up to date.
- [x] 3.0 data samples - (Contribute to #243)
- [x] 3.0 [edcd/coriolis-data](https://github.com/edcd/coriolis-data) entry - specials done. shields done. @UrukCan helping out with the rest.
- [x] Fixing incorrect engineering values (~~on hold until new journal mod format~~) #188
- [x] 3.0 Journal imports (without engineering) - Live on beta.
- [x] 3.0 internal slot changes.
- [x] Engineering mods - #158 
- [x] Chieftan - EDCD/coriolis-data#17
- [x] AX modules - #196 & EDCD/coriolis-data#19 (Thanks @Ghnuberath !)
- [x] New ships (Q1 Update) EDCD/coriolis-data#17
- [x] Figure out what to do with Edge/iexplore

**Comment by triccaj** [comment]
@willyb321 @strideynet  Um yea... so my redit post has allegedly attracted 4 more devs at this point. Obviously at times too many cooks can spoil the broth, but hopefully this can help you guys out. They have mentioned they will pull branchs and put up PRs :D. Hope this helps you out.

**Comment by triccaj** [comment]
Thanks for taking the initiative to intro yourself to the devs :D. 

I get the impression they're both super busy with real world things. I don't see any harm in you having a stab at whatever tickles your fancy really there isn't any sort of logical backlog that I can identify. I'm tempted to knock up a trello board for this project tbh..?

What are peoples opinions?

**Comment by strideynet** [comment]
A trello board isn't really needed when we have the issue tickets.

If you don't think you can immediately take a look at engineering, feel
free to have a go at any other issues.

**Comment by joelgarboden** [comment]
I've been watching this repo for a while, and playing Elite for a couple years. Coriolis is by far my favorite ship builder.

I mainly have infrastructure and systems experience but I'll definitely attempt what I can.

**Comment by mcdonnelldean** [comment]
@strideynet What needs to be done on the server side as part of the check mark above?

**Comment by strideynet** [comment]
Nothing. It's essentially ready but not something we want to implement at
this time. Want to get engineering imports ready first before introducing
async operations to Coriolis.

**Comment by mcdonnelldean** [comment]
@strideynet Makes sense, for engineering correction so (which looks to be the last one remaining), I'll start looking over on Friday and see how far I can get through it.

**Comment by willyb321** [comment]
@mcdonnelldean atm the journal import happens in `src/app/utils/JournalUtils.js` fyi.

**Comment by mcdonnelldean** [comment]
@willyb321 Perfect, that'll do. Though I may need a few more journals, I'm a pretty crappy player in terms of total engineered ships :D I see there are some importables in pastebin so I'll take a look at that over the weekend.

**Comment by willyb321** [comment]
@mcdonnelldean here's my FDL which is engineered: https://pastebin.com/sFnzGQtz

**Comment by willyb321** [comment]
Data left to enter:

Guardian / tech broker modules
Rapid fire, high capacity, double shot, life support and power plant
All utility except boosters
All optional except shield gen, hrp, dss

**Comment by willyb321** [comment]
Moving to #311
