### ISSUE TITLE
Coriolis 3.1 todo summary

### ISSUE THREAD

**Issue by willyb321** [EDCD/coriolis#311]
Previous issue #190	

# Summary of things left to do for 3.1
> Sorted by priority

- [x] Krait + challenger costs and any incorrect values https://github.com/edcd/coriolis-data
- [x] Guardian / tech broker modules (help wanted!) https://github.com/edcd/coriolis-data
- [ ] Coriolis serverside. https://github.com/edcd/Orbis

**Comment by burtonsimmons** [comment]
What help do you need for the guardian / tech broker modules? Screenshots of values?

**Comment by willyb321** [comment]
@burtonsimmons yep screenshots of values from outfitting of all the modules not in beta coriolis would be good. Cheers

**Comment by burtonsimmons** [comment]
Here should be a full set of screenshots for the Decontamination Limpet Controller, Large and Medium Gimballed Shock Cannon, Large and Medium Fixed Guardian Shard Cannon, Large Fixed Guardian Plasma Charger, Meta Alloy Hull Reinforcement Package, Guardian Hull Reinforcement Package, and Guardian Module Reinforcement Package.  (I don't have the fixed or turreted versions of the shock cannons or the turreted versions of the guardian weapons unlocked.)  

The pricing is at Jameson Memorial, and I'm single trade elite (not quite elite in combat or exploration yet!)

I hope this helps!  

https://imgur.com/a/Kna8JEJ

[Coriolis.zip](https://github.com/EDCD/coriolis/files/2169001/Coriolis.zip)

**Comment by felixlinker** [comment]
Some additional screenshots: https://forums.frontier.co.uk/showthread.php/440163-coriolis-help-thread?p=6927361&viewfull=1#post6927361

**Comment by felixlinker** [comment]
See #313 for more details

**Comment by felixlinker** [comment]
All modules have been added now.
