### ISSUE TITLE
Coriolis 3.2 todo summary

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#357]
Modules we still need data for are highlighted in bold.

Ships
- [x] Alliance Crusader

Weapons:
- [x] Large Dumbfire Missile
- [x] Large Seeking Missile
- [x] Large Torpedo Launcher
- [x] Large Multi Cannon (turret)

Weapons (human technology broker):
- [x] Small Shock Cannon (turret)
- [x] Small Shock Cannon (gimbal)
- [x] Small Shock Cannon (fixed)

Weapons (guardian tech broker):
- [x] Small Guardian plasma launcher (turret)
- [x] Small Guardian plasma launcher (fixed)
- [x] Small Guardian Shard Cannon (turret)
- [x] Small Guardian Shard Cannon (fixed)
- [x] Small Guardian Gauss Cannon (fixed)

**Comment by felixlinker** [comment]
Prices at Jameson Memorial with Elite discount.

![](https://cdn.discordapp.com/attachments/164411501166198784/484348403707412480/20180829230509_1.jpg)

![](https://cdn.discordapp.com/attachments/164411501166198784/484348412737749003/20180829230511_1.jpg)

![](https://cdn.discordapp.com/attachments/164411501166198784/484348449941225473/20180829230521_1.jpg)

![](https://cdn.discordapp.com/attachments/164411501166198784/484348458401005594/20180829230523_1.jpg)

![](https://cdn.discordapp.com/attachments/164411501166198784/484348496174907402/20180829230536_1.jpg)

![](https://cdn.discordapp.com/attachments/164411501166198784/484348505335529473/20180829230538_1.jpg)

**Comment by felixlinker** [comment]
Some more screenshots. Prices are from Founders World, i.e. with 10% + Elite discount. Screenshots are in german but that's no problem as I speak german.

![3](https://user-images.githubusercontent.com/9728715/45265171-8dd4a080-b447-11e8-9516-4f82effdeb5d.png)
![4](https://user-images.githubusercontent.com/9728715/45265172-8dd4a080-b447-11e8-9f35-2268b9546284.png)
![1](https://user-images.githubusercontent.com/9728715/45265173-8dd4a080-b447-11e8-8711-fbe4ba943d99.png)
![2](https://user-images.githubusercontent.com/9728715/45265174-8dd4a080-b447-11e8-87c7-dfe84f1b2744.png)

**Comment by schentuu** [comment]
![grafik](https://user-images.githubusercontent.com/4059333/45265338-a80f7e00-b449-11e8-9478-4c5e459f740d.png)

![grafik](https://user-images.githubusercontent.com/4059333/45265341-bbbae480-b449-11e8-8f33-f472cf15b486.png)

---------------------

![grafik](https://user-images.githubusercontent.com/4059333/45265345-d68d5900-b449-11e8-92d0-7f01624888fa.png)

![grafik](https://user-images.githubusercontent.com/4059333/45265351-e311b180-b449-11e8-9314-c410debf70a8.png)

**Comment by LesserHellspawn** [comment]
prices at Jameson Memorial

Shock Cannon turret:

![shock-ttop](https://user-images.githubusercontent.com/37193224/45321408-97443280-b545-11e8-9fa8-635965705c07.jpg)
![shock-tlow](https://user-images.githubusercontent.com/37193224/45321416-9c08e680-b545-11e8-90ff-f0408c772dca.jpg)

Shock Cannon gimbal:

![shock-gtop](https://user-images.githubusercontent.com/37193224/45321442-a925d580-b545-11e8-9110-a4c64098b125.jpg)
![shock-glow](https://user-images.githubusercontent.com/37193224/45321444-ac20c600-b545-11e8-8fb9-0ea90edb787b.jpg)

Shock Cannon fixed:

![shock-ftop](https://user-images.githubusercontent.com/37193224/45321460-ba6ee200-b545-11e8-9fd3-7d7fd78d96a0.jpg)
![shock-flow](https://user-images.githubusercontent.com/37193224/45321476-be026900-b545-11e8-9b62-62075f0b0fd8.jpg)

Shard Cannon turret:

![shard-ttop](https://user-images.githubusercontent.com/37193224/45321487-c78bd100-b545-11e8-800b-1f4148f04f15.jpg)
![shard-tlow](https://user-images.githubusercontent.com/37193224/45321496-cb1f5800-b545-11e8-9d5b-d963bc71c023.jpg)

Shard Cannon fixed:

![shard-ftop](https://user-images.githubusercontent.com/37193224/45321519-d70b1a00-b545-11e8-98cc-394b23405eed.jpg)
![shard-flow](https://user-images.githubusercontent.com/37193224/45321522-da060a80-b545-11e8-8f14-7a8c52591a9e.jpg)
